### ISSUE TITLE
[tracking] missing Falco regression tests

### ISSUE THREAD

**Issue by jasondellaluce** [falcosecurity/testing#7]
This is a tracker for all the tests related to the Falco CLI executable that are still missing.

Each of the following bullet point is a wonderful opportunity for easy first contributions. This tracker will be kept updated whenever PRs will get opened for any of the bullet points.

###  Falco command line
Test the behavior and expected output of the Falco CLI depending on its options, considered both individually and in combinations:
- [ ] **Commands printing information**:
  - [x] `-h`
  - [x] `--help`
  - [ ] `--support`
  - [x] `-i`
  - [x] `-L`
  - [ ] `-l`
  - [ ] `--list`
  - [ ] `--list-syscall-events`
  - [ ] `--markdown`
  - [ ] `-N`
  - [ ] `--gvisor-generate-config`
  - [ ] `--page-size`
- [x] **Metadata collection and container runtime**:
  - [x] `--cri` [DEPRECATED]
  - [x] `--disable-cri-async` [DEPRECATED]
  - [x] `-k` [DEPRECATED]
  - [x] `--k8s-api`  [DEPRECATED]
  - [x] `-K`  [DEPRECATED]
  - [x] `--k8s-api-cert`  [DEPRECATED]
  - [x] `--k8s-node`  [DEPRECATED]
  - [x] `-m`  [DEPRECATED]
  - [x] `--mesos-api`  [DEPRECATED]
- [x] **Falco event collection modes**:
  - [x] `-g`  [DEPRECATED]
  - [x] `--gvisor-config` [DEPRECATED]
  - [x] `--gvisor-root`  [DEPRECATED]
  - [x] `--modern-bpf`  [DEPRECATED]
- [ ] **Changers of Falco's behavior**:
  - [ ] `--disable-source`
  - [ ] `--enable-source`
  - [ ] `-A`
  - [ ] `-P`
  - [ ] `--pidfile`
  - [ ] `-p`
  - [ ] `--print`
  - [ ] `-b`
  - [ ] `--print-base64`
  - [ ] `-S`
  - [ ] `--snaplen`
- [ ] **Misc Falco features**:
  - [x] `-s`  [DEPRECATED]
  - [x] `--stats-interval`  [DEPRECATED]
  - [ ] `-U`
  - [ ] `--unbuffered`

###  Falco configuration fields
Test the behavior and expected output of Falco depending on the `falco.yaml` fields:
- [x] `watch_config_files`
- [ ] `libs_logger`
- [ ] `buffered_outputs`
- [ ] `syscall_event_timeouts`
- [x] `syscall_buf_size_preset`  [DEPRECATED]
- [x] `modern_bpf`  [DEPRECATED]
- [ ] `output_timeout`
- [ ] `outputs`
- [ ] `syslog_output`
- [ ] `file_output`
- [ ] `stdout_output`
- [ ] `webserver`
- [ ] `program_output`
- [ ] `http_output`
- [x] `metadata_download`

###  Falco environment variables
Test the Falco behavior on the supported environment variables and their priorities, also in combination with their args/configs/cmds counterparts:
- [x] `FALCO_K8S_API`  [DEPRECATED]
- [x] `FALCO_K8S_API_CERT`  [DEPRECATED]
- [x] `FALCO_MESOS_API`  [DEPRECATED]
- [ ] `FALCO_HOSTNAME`
- [ ] `FALCO_GRPC_HOSTNAME`
- [x] `FALCO_BPF_PROBE`  [DEPRECATED]
- [ ] `HOME` (used for bpf probe)

###  Other Falco things
Umbrella category for all the rest of things done by Falco not fitting in the above lists. This will likely be moved to another issue because they are more oriented to the integration with other tools (such as the driver loader), but I'm gonna list them here for now:
- Falco reaction to signals SIGINT, SIGUSR1, SIGHUP
- Collection of live events with kmod, bpf, modern-bpf, gvisor, userspace
- Collection of live events with multiple event sources active at the same
- Stress test with event generator, checking memory usage and event drops

**Comment by incertum** [comment]
@jasondellaluce we can remove the deprecated config or cmd args options.

**Comment by leogr** [comment]
This list must be reviewed considering the new deprecations:
- https://github.com/falcosecurity/falco/issues/2763
- https://github.com/falcosecurity/falco/issues/2840

@Andreagit97 @FedeDP could you help me with that please?

**Comment by incertum** [comment]
Check on some Legacy tests around enabling rules with or without tags and in combination with using the `enabled` key or not. Some tests seem to assert final rules that are enabled (e.g. `TestFalco_Legacy_DisabledTagsB`), other test could be missing it? e.g. `TestFalco_Legacy_DisabledRulesUsingEnabledFlag` or `TestFalco_Legacy_DisabledRuleUsingFalseEnabledFlagOnly` etc.

**Comment by FedeDP** [comment]
/remove-lifecycle stale

Marked `watch_config_files` as done since `testing` framework now tests it: https://github.com/falcosecurity/testing/pull/54
